
const actionTypes = Object.freeze({
    DOI_NGON_NGU:"DOI_NGON_NGU",

    LAY_ALLCODE_GIOI_TINH_THANH_CONG: "LAY_ALLCODE_GIOI_TINH_THANH_CONG",
    LAY_ALLCODE_GIOI_TINH_THAT_BAI: "LAY_ALLCODE_GIOI_TINH_THAT_BAI",

    LAY_ALLCODE_QUYEN_THANH_CONG: "LAY_ALLCODE_QUYEN_THANH_CONG",
    LAY_ALLCODE_QUYEN_THAT_BAI: "LAY_ALLCODE_QUYEN_THAT_BAI",

    THEM_NGUOI_DUNG_THANH_CONG:"THEM_NGUOI_DUNG_THANH_CONG",
    THEM_NGUOI_DUNG_THAT_BAI:"THEM_NGUOI_DUNG_THAT_BAI",

    LAY_TAT_CA_NGUOI_DUNG_THANH_CONG:"LAY_TAT_CA_NGUOI_DUNG_THANH_CONG",
    LAY_TAT_CA_NGUOI_DUNG_THAT_BAI:"LAY_TAT_CA_NGUOI_DUNG_THAT_BAI",

    LAY_1_NGUOI_DUNG_THANH_CONG:"LAY_1_NGUOI_DUNG_THANH_CONG",
    LAY_1_NGUOI_DUNG_THAT_BAI:"LAY_1_NGUOI_DUNG_THAT_BAI",

    XOA_NGUOI_DUNG_THANH_CONG:"XOA_NGUOI_DUNG_THANH_CONG",
    XOA_NGUOI_DUNG_THAT_BAI:"XOA_NGUOI_DUNG_THAT_BAI",

    SUA_NGUOI_DUNG_THANH_CONG:"SUA_NGUOI_DUNG_THANH_CONG",
    SUA_NGUOI_DUNG_THAT_BAI:"SUA_NGUOI_DUNG_THAT_BAI"

  });
  
  export default actionTypes;
  