
const actionTypes = Object.freeze({
    DOI_NGON_NGU:"DOI_NGON_NGU",

    LAY_ALLCODE_GIOI_TINH_THANH_CONG: "LAY_ALLCODE_GIOI_TINH_THANH_CONG",
    LAY_ALLCODE_GIOI_TINH_THAT_BAI: "LAY_ALLCODE_GIOI_TINH_THAT_BAI",

    LAY_ALLCODE_QUYEN_THANH_CONG: "LAY_ALLCODE_QUYEN_THANH_CONG",
    LAY_ALLCODE_QUYEN_THAT_BAI: "LAY_ALLCODE_QUYEN_THAT_BAI",

    THEM_NGUOI_DUNG_THANH_CONG:"THEM_NGUOI_DUNG_THANH_CONG",
    THEM_NGUOI_DUNG_THAT_BAI:"THEM_NGUOI_DUNG_THAT_BAI",

    LAY_TAT_CA_NGUOI_DUNG_THANH_CONG:"LAY_TAT_CA_NGUOI_DUNG_THANH_CONG",
    LAY_TAT_CA_NGUOI_DUNG_THAT_BAI:"LAY_TAT_CA_NGUOI_DUNG_THAT_BAI",

    LAY_1_NGUOI_DUNG_THANH_CONG:"LAY_1_NGUOI_DUNG_THANH_CONG",
    LAY_1_NGUOI_DUNG_THAT_BAI:"LAY_1_NGUOI_DUNG_THAT_BAI",

    XOA_NGUOI_DUNG_THANH_CONG:"XOA_NGUOI_DUNG_THANH_CONG",
    XOA_NGUOI_DUNG_THAT_BAI:"XOA_NGUOI_DUNG_THAT_BAI",

    SUA_NGUOI_DUNG_THANH_CONG:"SUA_NGUOI_DUNG_THANH_CONG",
    SUA_NGUOI_DUNG_THAT_BAI:"SUA_NGUOI_DUNG_THAT_BAI",

    LUU_THONG_TIN_NGUOI_DUNG:"LUU_THONG_TIN_NGUOI_DUNG",
    XOA_THONG_TIN_NGUOI_DUNG:"XOA_THONG_TIN_NGUOI_DUNG",

    THONG_TIN_HOA_DAT_HANG_TRANG_CHU:"THONG_TIN_HOA_DAT_HANG_TRANG_CHU",
    
    THEM_GIO_HANG_CHUA_DANG_NHAP:"THEM_GIO_HANG_CHUA_DANG_NHAP",
    SUA_GIO_HANG_CHUA_DANG_NHAP:"SUA_GIO_HANG_CHUA_DANG_NHAP",
    XOA_GIO_HANG_CHUA_DANG_NHAP:"XOA_GIO_HANG_CHUA_DANG_NHAP",

    THEM_MA_DON_HANG_CHUA_DANG_NHAP:"THEM_MA_DON_HANG_CHUA_DANG_NHAP",
    XOA_MA_DON_HANG_CHUA_DANG_NHAP:"XOA_MA_DON_HANG_CHUA_DANG_NHAP",

  });
  
  export default actionTypes;
  